apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: game-fleet-system

resources:
  - gameserverfleets.yaml
  - autoscalerpolicies.yaml
  - gameserverallocations.yaml
  - role.yaml
  - role_binding.yaml
  - controller.yaml
  - apiserver.yaml

images:
  - name: registry.cn-beijing.aliyuncs.com/noneedtostudy/game-fleet-director-controller
    newName: ghcr.io/Shaohan-He/game-fleet-director-controller
    newTag: latest
  - name: registry.cn-beijing.aliyuncs.com/noneedtostudy/game-fleet-director-apiserver
    newName: ghcr.io/Shaohan-He/game-fleet-director-apiserver
    newTag: latest
